### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pengli534**
This is where we explain why we need to make above changes
@jiaofenglp

### CODE REVIEW

**Comment by pengli534** [comment]
This is where we leave comments why do we want to pull the branch to master

**Comment by pengli534** [comment]
we may be able to provide multiple comments to the project we discuss

**Comment by pengli534** [comment]
@jiaofenglp can you please leave us some comments here?

**Comment by jiaofenglp** [comment]
Sometimes I introducue the changes we made in the commit. Is it ok?@pengli534

**Pull request merged**
